version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "research-app-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kssdwggh75fc"
s3_prefix = "research-app-demo"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

