AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws_lambdas

  Sample SAM Template for aws_lambdas

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PyModelFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: PythonModel
      CodeUri: py_model/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /py_model/{x}
            Method: get
  RModelFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RModel
      CodeUri: r_model/
      Handler: app.lambda_handler
      Runtime: provided
      Layers:
        - arn:aws:lambda:us-west-1:131329294410:layer:r-runtime-3_6_0:13
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /r_model/{x}
            Method: get
    Metadata:
      BuildMethod: makefile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PyRModelApi:
    Description: "API Gateway endpoint URL for Prod stage for Python and R model functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
